"""Add Phase 2 intelligence columns

Revision ID: 9b69eb1c7c92
Revises: 0001_create_tables
Create Date: 2026-06-14 12:13:51.531036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b69eb1c7c92'
down_revision: Union[str, None] = '0001_create_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('comments', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.add_column('comments', sa.Column('sentiment_label', sa.String(length=50), nullable=True))
    op.add_column('comments', sa.Column('technologies', postgresql.ARRAY(sa.String()), nullable=True))
    op.alter_column('comments', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_comments_id', 'comments', ['id'])
    op.add_column('posts', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.add_column('posts', sa.Column('sentiment_label', sa.String(length=50), nullable=True))
    op.add_column('posts', sa.Column('technologies', postgresql.ARRAY(sa.String()), nullable=True))
    op.alter_column('posts', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'comments_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('subreddits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subreddits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('posts', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('posts', 'comments_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('posts', 'technologies')
    op.drop_column('posts', 'sentiment_label')
    op.drop_column('posts', 'sentiment_score')
    op.drop_constraint('uq_comments_id', 'comments', type_='unique')
    op.alter_column('comments', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('comments', 'technologies')
    op.drop_column('comments', 'sentiment_label')
    op.drop_column('comments', 'sentiment_score')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
